# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'TwitterLite' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TwitterLite

  target 'TwitterLiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TwitterLiteUITests' do
    # Pods for testing
  end

end
